spring:
  application:
    name: batch-performance
  batch:
    job:
      name: ${job.name:NONE} # 기본 잡 실행 비활성화 -> 잡별 설정값 밑에 따로 작성
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:mem:batchdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.batch: INFO
    org.hibernate.SQL: DEBUG

job:
  config:
    create:
      name: orderCreateJob
      step: orderCreateStep
      chunk-size: 1000
    update:
      name: orderUpdateJob
      step: orderUpdateStep
      chunk-size: 1000
    statistics:
      name: orderStatisticsJob
      step: orderStatisticsStep
    no-offset:
      name: orderProcessNoOffsetJob
      step: orderProcessNoOffsetStep
      chunk-size: 1000
